name: Rebuild Hetzner VPS

jobs:
  rebuild:
    name: Rebuild VPS from Hetzner Pool
    runs-on: ubuntu-latest
    needs: allocate
    steps:
      - uses: actions/checkout@v3
      - run: pip install .
      - run: |
          mkdir ~/.ssh
          echo "${{ secrets.STAGING_SSH_KEY }}" >> ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          python3 main.py --hetzner-api-token ${{ secrets.HETZNER_API_TOKEN }} --rebuild --run-id $GITHUB_RUN_ID --vps ${{ needs.allocate.outputs.vps_name }}
