name: Rebuild Hetzner VPS

on:
  workflow_call:
    inputs:
      vps_name:
        description: the name of a Hetzner VPS, MUST be named after its domain name.
        required: true
        type: string

jobs:
  rebuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pip install .
      - run: |
          mkdir ~/.ssh
          echo "${{ secrets.STAGING_SSH_KEY }}" >> ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          python3 main.py --hetzner-api-token ${{ secrets.HETZNER_API_TOKEN }} --rebuild --run-id $GITHUB_RUN_ID --vps ${{ inputs.vps_name }}
